### ISSUE TITLE
Sync with latest Caffe

### ISSUE THREAD

**Issue by danst18** [NVIDIA/caffe#128]
I think syncing with the latest version of Caffe should be done soon. Some of the latest models, [Deep Residual Networks](https://github.com/KaimingHe/deep-residual-networks) for example, can't be used because some of the new layers are missing in this repo. It is a limitation not to be able to use these models with DIGITS.

**Comment by yangj1e** [comment]
+1
Some bug fixes have not been merged in this fork as well.

**Comment by drnikolaev** [comment]
You are welcome to try https://github.com/drnikolaev/caffe/tree/caffe-0.15
This is BVLC/caffe as of March 24th merged with NVIDIA/caffe 0.14.3
I'd appreciate any critics, bug reports etc.

**Comment by futurely** [comment]
https://github.com/NVIDIA/caffe/tree/caffe-0.15

**Comment by lukeyeager** [comment]
Caffe [v0.15.9](https://github.com/NVIDIA/caffe/releases/tag/v0.15.9) is our latest official release.

There are deb packages available. Installation instructions here:
https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/UbuntuInstall.md

**Comment by mrgloom** [comment]
This [repo](https://github.com/KaimingHe/deep-residual-networks) only have deploy.prototxt, also I tried [this repo](https://github.com/jay-mahadeokar/pynetbuilder/tree/master/models/imagenet) but seems it doesn't work in DIGITS. Technically it works, but network not learning, maybe because of Batch Norm layer? Prototxt structure is correct but maybe 'meaning' of parameters\layers changed in Caffe master?

Tested with nvidia caffe

~~~
DIGITS version:

`./digits-devserver --version`

4.1-dev

Caffe version:

`git status`

branch caffe-0.15

`git log -n 1`

commit e638c0b1cb19afff50d830ce87cc1898f18568fd
Author: Sergei Nikolaev <snikolaev@nvidia.com>
Date:   Wed Aug 31 14:32:28 2016 -0700
Mark 0.15.13
~~~
