### ISSUE TITLE
Next planned release

### ISSUE THREAD

**Issue by npanpaliya** [NVIDIA/caffe#204]
Hi All,

I want to know about the next release of NVIDIA/caffe. When is it planned, will it be 16.0 or 15.10?

**Comment by lukeyeager** [comment]
We're currently working on finalizing the v0.15 release. Deb packages should be available very soon.

**Comment by npanpaliya** [comment]
@lukeyeager, thanks. But did you mean v0.16 release? Because v0.15.9 tag is already present in the repo. But I also don't see v0.15.0 release tag.

**Comment by lukeyeager** [comment]
There's a delay between when we tag the code and when we release official packages. That's because we put them through a QA process.

Caffe 0.15.9 is now officially released. Follow these instructions to get repository access and install:
https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/UbuntuInstall.md
