### ISSUE TITLE
PythonLayer is not implemented in Multi-GPU training

### ISSUE THREAD

**Issue by RSly** [NVIDIA/caffe#305]
Hi
I am using the latest nv-caffe and get the error
PythonLayer is not implemented in Multi-GPU training.

It seems that this issue has been fixed in bvlc caffe in
BVLC/caffe#4563
and
BVLC/caffe#2936

is there a special reason this change has not been merged in nv-caffe?

I think this is a great improvement to caffe and can save a huge amount of training time with python loss and layers.

Ref: https://github.com/NVIDIA/DIGITS/issues/1570

**Comment by drnikolaev** [comment]
@RSly it's here: https://github.com/NVIDIA/caffe/tree/caffe-0.16

**Comment by RSly** [comment]
@drnikolaev thanks a lot! I will test it soon

Does it work out of the box or will I need a caffe.py as in 
https://github.com/BVLC/caffe/blob/master/python/train.py
to train on multi-gpus with python data layer?

**Comment by RSly** [comment]
Hi @drnikolaev 
I tested this and it all works like a charm!  bravo!
Also no need for caffe.py

**Comment by drnikolaev** [comment]
Cool, thanks for confirming!

**Comment by LinHungShi** [comment]
@RSly @drnikolaev  How do you enable training with multiple gpu in Python? I can't find any tutorial for multi-gpu training in Python, and the only thing that I found relevent in _caffe.cpp is set_devices which seems not useful for mutl-gpu training. I know that caffe.cpp has support for python layers, but I'd like to see if there any way I can do it in Python rather than C++. Thanks
