### ISSUE TITLE
Performance Issues using FP16

### ISSUE THREAD

**Issue by 7oud** [NVIDIA/caffe#308]
I tested the performance using FP16 type, it seemed that FP16 did not faster than FP32 but slower.

Environment:
- Ubuntu 14.04, CUDA 8.0, cudnn5.1.5
- Pascal GTX 1080 GPU
- NVIDIA/caffe branch: experimental/fp16
- with option NATIVE_FP16 := 1
- comparing inference time using "tools/caffe time ..." & "tools/caffe_fp16 time ..." 
- model: "models/bvlc_reference_caffenet/deploy.prototxt"

Results
- speed: caffe using about 9ms, but caffe_fp16 using about 15ms
- memory: caffe_fp16 using fewer memory than caffe

**Comment by drnikolaev** [comment]
@7oud please try new release: https://github.com/NVIDIA/caffe/tree/caffe-0.16

**Comment by psyhtest** [comment]
@7oud, @drnikolaev I believe this is due to the fundamental fp16 limitation of the GTX 1080 GPU, not due to the branch used. Please take a look at [dividiti's public benchmarking results](https://github.com/dividiti/ck-caffe-nvidia-gtx1080) (released with approval from General Motors), in particular, [here](https://nbviewer.jupyter.org/github/dividiti/ck-caffe-nvidia-gtx1080/blob/master/script/analysis/ck-caffe-nvidia-gtx1080.20170518.ipynb#plot_models_cudnn).
