### ISSUE TITLE
NVCaffe User Guide - shuffle parameter

### ISSUE THREAD

**Issue by TimoSaemann** [NVIDIA/caffe#483]
Hi @drnikolaev 

In the NVCaffe User Guide it says that the _shuffle_ parameter (of the DataParamter) is ignored if the _cache_ parameter is set to false. I wonder why the parameter _shuffle_ should depend on the parameter _cache_? Furthermore, I don't find any condition in the image_data_layer.cpp where _cache_ could affect the parameter _shuffle_. I think _cache_ affects _threads_, but not _shuffle_. 
Am I missing something?

Best,
Timo

**Comment by drnikolaev** [comment]
Hi @TimoSaemann 
ImageDataLayer does support shuffle without caching. Because it reads images in any order from disk. However, DataLayer reads sequential databases like LMDB. It's like tape recorder. DataLayer has to read the whole dataset to RAM (i.e. to cache it) in order to shuffle it effectively. One might argue that LMDB supports random access. But performance is not acceptable (I tried it).

**Comment by TimoSaemann** [comment]
Ok, thanks for your response!
